### ISSUE TITLE
Figs 1,2 and 7 too similar?

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/treestats_ms#11]
Picking up Peter's note from the text:

> Question: Figures 1, 2 and 7 show the same sort of thing (fig 1 is a site stat, aiming to give the
general overview; figs 2 and 7 are branch stats). Should they be more similar? Do we need all of these?

Unless we've got some hard limit on the number of figures, I think we should keep all three. The emphasis is slightly different in 2 and 7 (explaining how the stat works vs how the algorithm works). This isn't going to be obvious to people, I think, so a little repetition is OK.

**Comment by petrelharp** [comment]
Sounds good. We can revisit later, of course.
