### ISSUE TITLE
Big O analysis

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/treestats_ms#12]
I'm not quite sure what the right Big O analysis for the branch stat algorithm is. I know that it's something like
```
(n + rho log_e n) * log_2 n
```

Do we just treat log_e and log_2 as the same for big O? 

This should be the model we fit to the data too.

**Comment by petrelharp** [comment]
> Do we just treat log_e and log_2 as the same for big O?

log_2(n) = log_e(2) * log_e(n), so yes.

And yes, this seems right.
