### ISSUE TITLE
discuss summary function restrictions

### ISSUE THREAD

**Issue by petrelharp** [petrelharp/treestats_ms#17]
As discussed in #16, I will add a paragraph about the motivation behind strict, and other considerations (as started [here](https://github.com/tskit-dev/tskit/issues/357)). This should explain why/when you'd want to restrict to strict functions. Will put this before the "Duality..." section.

**Comment by petrelharp** [comment]
I've added this paragraph, but @molpopgen note that this was already discussed right [here](https://github.com/petrelharp/treestats_ms/blob/1d80fe82568c36c37e6aeb97087e9803b0be75c1/treestats_paper.tex#L261). We should evaluate whether the duplication is good or not.

**Comment by molpopgen** [comment]
Yep, but that's just the bit about "fixed or not".  But we still seem to be
talking past each other on several points.  For example, that criterion was
stated yesterday to not apply to polarised stat functions, which I then
asked "why not?", but we didn't get back to that.

**Comment by petrelharp** [comment]
> Yep, but that's just the bit about "fixed or not".

Well, that line explains the motivation behind "strict", if rather concisely, which is what I wrote in this issue that we wanted to explain. What else did you want to discuss?

> that criterion was stated yesterday to not apply to polarised stat functions, which I then asked "why not?", but we didn't get back to that.

I'm not finding that statement, but maybe I got mixed up: the code *does* evaluate the "strict" condition even if the statistic is polarised. Maybe this is not as it should be, though, because for polarised statistics you should be able to use fixed, derived mutations (so if `polarised and strict` then we should only check if `f(0) = 0`).  Do you agree with this?

**Comment by molpopgen** [comment]
> I'm not finding that statement, but maybe I got mixed up: the code _does_ evaluate the "strict" condition even if the statistic is polarised. Maybe this is not as it should be, though, because for polarised statistics you should be able to use fixed, derived mutations (so if `polarised and strict` then we should only check if `f(0) = 0`). Do you agree with this?

Yes, this is what I was wanting to discuss.  I think this would be an improvement. The thread started [here](https://github.com/petrelharp/treestats_ms/pull/16#discussion_r322015744)

**Comment by molpopgen** [comment]
Actually, I want to amend my previous comment. I think that the preferred interface would be that the sample sizes are passed to the summary function. Along with that, strict would always be true. Then, a statistic is defined by default as only with respect to data contributing to differences between individuals. that would solve all of the issues I have at the current interface. I also think it works well for the two and four way statistics. ultimately I want there to be one way to write a summary function and that one way always works with the default parameters to this statistics functions

**Comment by petrelharp** [comment]
I agree, it would be more convenient to have sample sizes available to the summary function in `sample_count_stat( )`. And more generally to have total weights available to `general_stat`. Does this affect how we present things in the paper?

**Comment by molpopgen** [comment]
> Does this affect how we present things in the paper?

No, it should not.  Making those changes to the API would result in the API being as general as the presentation described in the paper, which I think would/should be the near-to-mid-term goal.

**Comment by petrelharp** [comment]
> No, it should not. Making those changes to the API would result in the API being as general as the presentation described in the paper, which I think would/should be the near-to-mid-term goal.

I would like to have total weights, abstractly, but I am loathe to change the API:  we've released it, in tskit 0.2.1, and this change doesn't affect what is possible to compute.  I'm not sure what you mean by "as general as in the paper": the implementation is as general as what's in the paper.

**Comment by jeromekelleher** [comment]
I'm not following the arguments here, but I'm not against changing the general stats API a little if it makes things easier to compute and understand. I doubt anyone is using the general forms so far, and if there's changes that need to be made this is the time to do it.

**Comment by molpopgen** [comment]
@jeromekelleher 

The basic issue is how to write a function that works with the default behavior of `strict=True`.  in essence, it boils down to being convenient to pass the sample list sizes to the functions.  So, instead of just receiving the weights in each sample group, the weights + the sample list sizes would be passed in.  Allowing this helps implement functions that do indeed return zero when x[i] == nsam[i], etc..

**Comment by jeromekelleher** [comment]
So, we'd like to have the signature be
```python
def f(x, n):
     return something
```
where n is an array of the same length as x, and gives the sizes of the sample sets?

If so, then we can support both this and the original definition easily enough in the general API using introspection. If the summary function takes one argument, supply it with x. If two, give it x and n.

There's probably summary functions that we genuinely don't care about n in, so it's probably good to support both. It's not urgent to do this in terms of the paper though, I think.
