### ISSUE TITLE
Y axis units in Fig 5.

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/treestats_ms#25]
I'll confirm with Leo what the branch length units are.

Do we need to the tree sequence to plot the data, or is there a CSV file of the data in the repo that we can use to plot from?

**Comment by petrelharp** [comment]
You should be able to plot [like this](https://github.com/petrelharp/treestats_ms/blob/master/figures/Makefile#L8) using pre-computed values; if it doesn't work I've forgot to check something into git.

**Comment by petrelharp** [comment]
Whoops; I've forgot to check that in. I'll add those files.

**Comment by petrelharp** [comment]
Added just now.

**Comment by jeromekelleher** [comment]
Just confirmed that the units are generations with Leo. I tried to play around with the plots, but the data doesn't seem to be there (missing the TSV file?). We're probably going to get some criticism on just showing the two plots here, so I think there's two things we can do:

1. Do a more indepth analysis where we try to do some correlations, or find a way of plotting both on the site and branch in the same figure in a way that shows the differences. This could be as simple as plotting one divided by the other (also, chiming with your comment about mutation rate, @petrelharp?)
2.  Say, "They look pretty similar, but not exactly the same. We know this isn't a robust or quantitative statement, future work, yadda yadda."

Your call, I think, @petrelharp.

**Comment by jeromekelleher** [comment]
We probably don't need to redo these figures, I think, but there is definitely a little cosmetic work needed (including units for Y axes). Also, there's a \\plr{} message still in the caption.

**Comment by petrelharp** [comment]
I've added the ratio (couldn't help it). And added the tsv, which had eluded me before.
