### ISSUE TITLE
more explanation

### ISSUE THREAD

**Issue by petrelharp** [petrelharp/treestats_ms#27]
Useful comments from @apragsdale:

1. In the intro in Framework and statistics, you dive straight into ways of
generalizing statistics to compute them over a tree, talking about propagating
weights up trees, using ``nodes'' and ``edges'' and other tree terminology, but
you haven't yet introduced the tree sequences. Might make sense to reorder this
section and put \section{Tree sequences} before this so that we have the
terminology and data structure in mind before talking about computing things on
trees?

2. When computing statistics, sometimes you have the factor $\frac{1}{L}$ and
sometimes not - is there a reason why sometimes you normalize by sequence
length, but sometimes not? 

This was an error in at least one definition in this version; I think everything is consistent now...

3. Similarly, in the application to $f_4$ statistics
from simulated data, you report a significant negative value of $-700$ (not
scaled by sequence length).

It is scaled by sequence length; I've hopefully clarified this in 41b1e2080 and 6a5a008.

4. Factor of 2 in Example 2, since we don't care about the order of drawing
alleles when measuring heterozygosity. Similarly, in Example 3, should
$f(x_1,x_2) = \frac{x_1(n_2-x_2)}{n_1n_2} + \frac{(n_1-x_1)x_2}{n_1n_2}$ to
account for the two ways of finding differences?

We clearly need to explain why this is correct as is.

5. Figure 5 is a bit confusing - why are the scales so different between site and
branch stats? If we want to compare the site to branch statistics from each
inferred tree sequence, it would be helpful to see them on top of each other
(maybe just using one or two sampling locations, and putting the rest in the
supp?). Probably would need to normalize the branch stats by sequence length? I
always find it hard to eyeball between figure panels. 

Also needs more explanation, at least. Added something (that needs confirming) in 0455528.

**Comment by molpopgen** [comment]
The figure reference in https://github.com/petrelharp/treestats_ms/commit/41b1e2080d5e5c8855a3a9563fffcecba095bf14 appears to be incorrect.  \ref{fig:introf4 is Figure 2, not a supplemental figure.

**Comment by molpopgen** [comment]
Actually, something totally bizarre is happening with the internal links.  The \ref is indeed correct, but it goes to the wrong figure when I click on it, with both Zathura and with evince.  Odd.

**Comment by petrelharp** [comment]
Internal links are working for me. They link to the top of the caption, not the fig, but there doesn't seem to be a way to fix that...

**Comment by jeromekelleher** [comment]
I think we've covered all the issues here; shall we close?

**Comment by petrelharp** [comment]
I just re-did Fig 5, so yes, I think so!
