### ISSUE TITLE
ylim too small in fig S1.

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/treestats_ms#28]
Lines are shoved up against the top and the legend obscured (I tried to fix, but couldn't figure out how to replot them).

**Comment by petrelharp** [comment]
Apologies; I haven't got the underlying data stored, and the tree sequence is 17M.

And, I cannot get matplotlib to respect my `set_ylim( )`. I'm probably doing something dumb, but don't want to figure out what it is right now. I think we can ignore this for now.

**Comment by petrelharp** [comment]
Fixed this.
