### ISSUE TITLE
Figure 2 not quite in line with text?

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/treestats_ms#30]
In the text, we say "Here, we see how the f 4 site statistic assigns a weight to each mutation depending on its frequency in each of
the four sample sets, and how the corresponding branch statistic assigns the same weight to those branches".

But, I can't really see the same weights being assigned in Figure 3. It's not obvious to me what's going on here.

**Comment by petrelharp** [comment]
I (hopefully) fixed this by adding the time scale to the y-axis, so you can see that the number by the branch is the mutation's weight multiplied by the branch length.

**Comment by jeromekelleher** [comment]
Ah, much better, thanks.
