### ISSUE TITLE
Figure 1 comments

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/treestats_ms#38]
Here are some comments from Konrad (I'm confused by some of these too, I have to say; why 10 sites? Is it 7 or 5 mutations?):

- In the example in Fig. 1 the correspondence between node weights and the SFS could be made even clearer; i.e. why not just say that the node weights are the entries of the unfolded jSFS?
- Fig 1 legend say seven muts, should be 5 no?
-  f(a,b) could be given in general terms as f(a,b)= (a/n_red (1-b/n_blue)). This would make the link with both the one pop case (i.e. p(1-p)) and the 4 pop example (f4) really clear.
-  I found setting the total number of sites to 10 in the Fig1 toy example confusing. Would it be easier to just keep things generic, i.e. a number of sites L? If you want to assume a real length, why not something larger and realistic (for humans), say 1kb? That way folk don't get sidetracked worrying about infinite sites.

**Comment by petrelharp** [comment]
> I found setting the total number of sites to 10 in the Fig1 toy example confusing. Would it be easier to just keep things generic, i.e. a number of sites L? 

I did this to get a concrete number out at the end, but it could also be L...
