### ISSUE TITLE
Figure 2A redundant?

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/treestats_ms#48]
Now that Figure 1 is much simpler, I wonder if Figure 2A (showing weights propagated up the tree) is needed. We only refer to it fleetingly in the text, and the caption only barely refers to it at all. Most of the caption is talking about 2B, then it talks about 2A and goes back to 2B. Further, readers might be confused about why we're omitting the weights in the right subtree and might think this is somehow significant.

I think the simplest thing is to remove 2A entirely and just make this an example of computing divergence. We can mention in the caption that weights are vector valued here.

**Comment by jeromekelleher** [comment]
We could consider removing this short paragraph referring to Fig 2 (I'm not sure it adds much), and moving the figure down the file to be closer to the definition of Divergence.

**Comment by petrelharp** [comment]
What if we separate out Fig 2A to be a standalone figure, say a few more words about it, and move the rest of Figure 2 lower down?

**Comment by jeromekelleher** [comment]
Sure, that would work well. I was a bit worried about not explaining weights in the abstract at all.
