### ISSUE TITLE
empirical diversity?

### ISSUE THREAD

**Issue by petrelharp** [petrelharp/treestats_ms#5]
I've just added something looking at and talking about comparisons between site diversity and branch diversity on 1kG chr20 from tsinfer, GEVA, and Relate.  I'm hoping this adds to the interest by looking at the branch/site comparison in real data, and gives a reason to talk more about the caveats to the neutral-infinite-sites assumption.  What do you think, @jeromekelleher, @molpopgen?  If we want to keep this, we need to, I think

 - recompute with the same window size
 - also compute some other statistics (`f2`?)  to put in the supplement

**Comment by jeromekelleher** [comment]
I'm not sure putting in tsinfer+GEVA is entirely fair as we've not tested it at all, and I'm sure there's some improvements we could make easily enough. Don't want to give the impression that branch lengths computed this way are inherently terrible. Branch lengths from tsinfer itself are next to meaningless, I would have thought.

Showing that Relate is doing a really good job seems like a nice figure though?

**Comment by jeromekelleher** [comment]
Just read the text there - so this is misleading I think. GEVA isn't estimating node times in the tree, it's estimating the age of alleles which we then use to time the corresponding ancestors in tsinfer, in turn giving node times in the tree (those corresponding to generated ancestors). We put this in as a crude first pass just to see what would happen, but I'm sure there's stuff we've forgotten about (like path compression, I've just realised).

**Comment by petrelharp** [comment]
So: we should add some clarification and more caveats about the methods being early-days. I also should have said that it's not actually clear that Relate does better 'cause we have to plot both of them with the same windows anyhow. With that, how's the concept?

**Comment by jeromekelleher** [comment]
> So: we should add some clarification and more caveats about the methods being early-days. I also should have said that it's not actually clear that Relate does better 'cause we have to plot both of them with the same windows anyhow. With that, how's the concept?

Sure, if guess if we caveat it well then there's no harm. What might be interesting would be to also show some sort of node diversity, showing that Relate is inferring way too many ancestors, or that they're sort of spread around the times of what might be the true ancestors. tsinfer + GEVA should be better at this. This would give an application of the node stats as well, which might be a bit opaque to people.

**Comment by petrelharp** [comment]
I've implemented masking for the 1kg data and rejiggered the script so that it runs with arguments.  @jeromekelleher, could you get me the Relate tree sequence, or run these yourself on it? I think all you need to do is
```
cd figures/1kg
make    # gets mask and converts it 
cd ..
make (name of relate .trees file).branch.1000000.diversity.pdf
```

Of note: at first I was going to do the masking with `dice` but there's a ridiculous number of regions (tens of thousands), which I was worried would mess up all the trees, so instead I just computed statistics in the tens of thousands of windows and combined the appropriate ones, using numpy tricks.

**Comment by jeromekelleher** [comment]
I had a go at this @petrelharp, but I've had to recode the metadata in the relate trees and it's a bit messy. TBH this is too slow and frustrating to work on remotely on my antique laptop. Do you mind if we shelve this until I get back in ~10 days?

**Comment by petrelharp** [comment]
Sure, although it's in my head now, so it might be more efficient if I could get the tree sequences somehow? I think I could deal with it quickly.

**Comment by petrelharp** [comment]
I've updated the repo with plots made in the same way in 1Mb windows with all the methods, properly masked, FYI. I think I need to compute correlation coefficients between them also, since it's no longer so dramatically obvious which one is doing better. I'm going to close this now, though.
