### ISSUE TITLE
Be more precise about 'above' and 'below' nodes?

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/treestats_ms#8]
Unfortunately people don't agree on what above and below a node in a tree mean (e.g., Felsenstein draws trees upside down). Do we go through the paper being more precise, using things like "all samples descending from a node u" (rather than "all samples below a node u"), or do we explain at the start when we're setting out terminology which way around we think about trees.

I'm inclined towards being more precise, but we'll have to change a lot of stuff. Opinions?

**Comment by molpopgen** [comment]
Given the intended target journal, I think that it'll be simpler to state the convention early and then use the simpler language throughout

**Comment by petrelharp** [comment]
I'm pretty much always in favor of finding a concise way to say the precise thing instead of the shorthand, and don't mind changing things. This has the benefit of reminding people what the trees mean (eg "descended from" instead of "below").

**Comment by petrelharp** [comment]
Also I am happy to do this.

**Comment by jeromekelleher** [comment]
OK, I'm happy for you  to make the call on this @petrelharp.
