### ISSUE TITLE
Notation: use Iversonians for complicated sums?

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/treestats_ms#9]
As a dyed-in-the-wool Knuthian, I found myself wanting to use [Iversonian brackets](https://en.wikipedia.org/wiki/Iverson_bracket) in some of the more complicated sums. So, e.g., rather than
```tex
\sum_{v: g_j(v) = a} w(v)
```
do 
```tex
\sum_{v} w(v)[g_j(v) = a]
```

Heresy?

**Comment by molpopgen** [comment]
I prefer this notation, and its I(x) variant.  The down side is that you will have to rewrite all the algorithms in MIX!

**Comment by petrelharp** [comment]
Hm. I'm not opposed, but there are two downsides: this is not common (I have not seen it ever outside of Knuth), and writing it as a restriction on the sum makes it more clear how many things you are summing over. Do you have counter-arguments in favor of the brackets? larger fonts?

**Comment by jeromekelleher** [comment]
Nah, let's leave it as it is. We're using square brackets for other stuff (intervals and table row access), so it'll just end up being confusing to most people probably.
